### ISSUE TITLE
Build steps for Rust Rover

### ISSUE THREAD

**Issue by georgik** [Jozott00/wokwi-intellij#8]
Very nice piece of work @Jozott00 .

I was testing the build and deployment to Rust Rover and here are my findings.

It's necessary to add section like this into `README.md` in order to build the plugin
```
<!-- Plugin description -->
Wokwi plugin
<!-- Plugin description end -->
```

Build: `./gradlew buildPlugin`

The output artifact is in `build/distributions/wokwi-intellij-0.0.1.zip` and it's necessary to install it manually to Rust Rover.

Using `./gradlew runIde` opens IntelliJ Idea and I was not able to find a way how to tweak it to open the Rust Rover IDE.

**Comment by Jozott00** [comment]
The new version is on the main branch now. I will publish it on Jetbrains marketplace in the next couple of days.
