### ISSUE TITLE
[FEATURE-REQUEST] Curious on Rust Rover compatibility

### ISSUE THREAD

**Issue by lure23** [Jozott00/wokwi-intellij#80]
**Is your feature request related to a problem? Please describe.**

I found out about the Wokwi plugin today, visited [this site](https://plugins.jetbrains.com/plugin/23826-wokwi-simulator) and it says:

![image](https://github.com/user-attachments/assets/215f5349-0d83-42eb-be30-f7bc0c4832aa)

I presume this means that once the plugin supports IntelliJ 2024.2 platform, things will change (for a while)? What are the plans for the future, and Rust Rover in particular?

**Describe the solution you'd like**

Just wanting to understand the roadmap. Not asking for anything.

**Describe alternatives you've considered**

Using Wokwi separately (I do have an account).

**Comment by ralbear** [comment]
Same here with IntelliJ IDEA 2024.2.1
<img width="452" alt="image" src="https://github.com/user-attachments/assets/c63080d1-c3bc-45dd-a881-5c423d5d6ff9">

**Comment by Jozott00** [comment]
Sorry for the late reply. #81 adds support for the 2024.2 IntelliJ Platform. This includes RustRover 2024.2.

You should be able to install wokwi-intellij on RustRover now 🙂.
